"M: app":
  - stepCalc/lib/app/**/*
"M: auth":
  - stepCalc/lib/auth/**/*
"M: content":
  - stepCalc/lib/content/**/*
"M: creation":
  - stepCalc/lib/creation/**/*
"M: explore":
  - stepCalc/lib/explore/**/*
"M: calc":
  - stepCalc/lib/calc/**/*
"M: messenger":
  - stepCalc/lib/messenger/**/*
"M: settings":
  - stepCalc/lib/settings/**/*
"P: app":
  - stepCalc/**/*
