name: pizzaCalc
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.22.0 <1.23.0"

dependencies:
  basics: ^0.4.0+1
  black_hole_flutter: ^0.2.14
  bloc: ^6.0.1
  camera: ^0.5.8+7
  cloud_firestore: ^0.14.0-dev.1
  cloud_functions: ^0.6.0
  collection: ^1.14.11
  email_validator: ^1.0.5
  firebase_auth: ^0.18.0-dev.2
  firebase_core: ^0.5.0-dev.2
  firebase_storage: ^4.0.0
  flutter:
    sdk: flutter
  flutter_deep_linking: ^0.1.2
  flutter_local_notifications: ^3.0.1+5
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^0.11.0+1
  get_it: ^4.0.4
  health: ^2.0.9
  image: ^2.1.18
  infinite_scroll_pagination: ^1.1.1
  loading_overlay: ^0.2.1
  logger: ^0.7.0+1
  logger_flutter: ^0.7.1
  meta: ^1.1.8
  navigation_patterns:
    git:
      url: https://github.com/JonasWanke/navigation_patterns.git
      ref: b1841ad
  outline_material_icons: ^0.1.1
  package_info: ">=0.4.1 <2.0.0"
  percent_indicator: ^2.1.8
  streaming_shared_preferences: ^1.0.1
  path_provider: ^1.6.18
  test: ^1.15.0
  time_machine: ^0.9.13
  todo: ^1.0.2
  url_launcher: ^5.7.2

dev_dependencies:
  build_runner: ^1.10.1
  extra_pedantic: ^1.2.0
  flutter_test:
    sdk: flutter
  freezed: ^0.11.4
  intl_utils: ^1.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/

  fonts:
    - family: FiraSans
      fonts:
        - asset: assets/fonts/FiraSans-Regular.ttf
        - asset: assets/fonts/FiraSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/FiraSans-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
